### Fetch all tasks


GET http://localhost:3300/tasks
Content-Type: application/json


POST http://localhost:3300/tasks
Content-Type: application/json

{
    "title":"Task1",
    "description":"This is a task 1",
    "date":"2023-05-17T12:00:00Z",
    "priority":"normal",
    "status":"todo"
}