### Fetch all tasks


GET http://localhost:3300/tasks
Content-Type: application/json


POST http://localhost:3300/tasks
Content-Type: application/json

{
    "title":"Task3",
    "description":"This is a task 3",
    "date":"2023-05-17T16:36:00Z",
    "priority":"normal",
    "status":"completed"
}